---
# Model instantiated with hydra.utils.instantiate
#  https://hydra.cc/docs/advanced/instantiate_objects/overview/

# Must be an instance of lightning.LightningModule
#  https://lightning.ai/docs/pytorch/stable/common/lightning_module.html

_target_: atsc.counting.models.baseline.Baseline
n_channels: 4
n_mels: 96
n_gcc: 48
stft_params: # https://pytorch.org/docs/stable/generated/torch.stft.html
    hop_length: 160
melscale_params: # https://pytorch.org/audio/main/generated/torchaudio.transforms.MelScale.html
    n_mels: ${model.n_mels}
optimizer:
    _partial_: true
    _target_: torch.optim.Adam
    lr: ${training.learning_rate}
