---
# Synthetic dataset, segments generated on the fly
_target_: atsc.counting.data.SyntheticTrafficDataset
sim_events_root: ${simulation.output_folder}
event_duration: ${simulation.event_duration}
random: false
traffic_model_path: ${traffic.val.output_path}
